
def main():
    startApplication("Q2")
    clickLink(waitForObject(":Analysis_HTML_Object"))
    snooze(5)
    #$doubleClick(waitForObject(":{type='SPAView' unnamed='1' visible='1' window=':_MainWindow'}.DOCUMENT.HTML1.BODY1.DIV2.DIV3.DIV1.SECTION1"), 10, 26, 0, Qt.LeftButton)
    clickButton(waitForObject(":_submit"))
    clickLink(waitForObject(":Filter 001_HTML_Object"))
    mouseClick(waitForObjectItem(":_WebCore::QtWebComboBox", "4 weeks ago"), 102, 15, 0, Qt.LeftButton)
    selectOption(waitForObject(":_select-one_5"), "4 weeks ago")
    clickButton(waitForObject(":Add Data_submit"))
    clickButton(waitForObject(":_submit_2"))
    doubleClick(waitForObject(":{type='SPAView' unnamed='1' visible='1' window=':_MainWindow'}.DOCUMENT.HTML1.BODY1.DIV2.DIV2.DIV1.DIV1.SECTION1.DIV1.DIV1.DIV1.DIV4.DIV1.DIV1"), 1271, 253, 0, Qt.LeftButton)
    doubleClick(waitForObject(":{type='SPAView' unnamed='1' visible='1' window=':_MainWindow'}.DOCUMENT.HTML1.BODY1.DIV2.DIV2.DIV1.DIV1.SECTION1.DIV1.DIV1.DIV1.DIV4.DIV1.BUTTON1.I1"), 4, 10, 0, Qt.LeftButton)
    clickLink(waitForObject(":Save as PDF_HTML_Object"))
    doubleClick(waitForObject(":{type='SPAView' unnamed='1' visible='1' window=':_MainWindow'}.DOCUMENT.HTML1.BODY1.DIV2.DIV3.DIV1.SECTION1"), 24, 33, 0, Qt.LeftButton)
    mouseClick(waitForObject(":{type='SPAView' unnamed='1' visible='1' window=':_MainWindow'}.DOCUMENT.HTML1.BODY1.DIV2.DIV3.DIV1.SECTION1"), 24, 33, 0, Qt.LeftButton)
    doubleClick(waitForObject(":{type='SPAView' unnamed='1' visible='1' window=':_MainWindow'}.DOCUMENT.HTML1.BODY1.DIV2.DIV3.DIV1.SECTION1.HEADER1.I1"), 8, 9, 0, Qt.LeftButton)
    mouseClick(waitForObject(":{type='SPAView' unnamed='1' visible='1' window=':_MainWindow'}.DOCUMENT.HTML1.BODY1.DIV2.DIV3.DIV1.SECTION1.HEADER1.I1"), 8, 9, 0, Qt.LeftButton)
